(source "gnu" "https://elpa.gnu.org/packages/")
(source "marmalade" "https://marmalade-repo.org/packages/")
(source "melpa" "https://melpa.org/packages/")
(source "melpa-stable" "https://stable.melpa.org/packages/")
(source org)

(depends-on "anzu")
(depends-on "async")
(depends-on "auto-highlight-symbol")
(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "epl")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "flycheck-pyflakes")
(depends-on "flymake-cursor")
(depends-on "git-commit")
(depends-on "highlight-symbol")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "init-loader")
(depends-on "isearch+")
(depends-on "magit")
(depends-on "magit-popup")
(depends-on "migemo")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "package-build")
(depends-on "pallet")
(depends-on "pkg-info")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "s")
(depends-on "shut-up")
(depends-on "smartrep")
(depends-on "with-editor")
